/*
 *    SAM-QFS_notice_begin
 *
 *      Solaris 2.x Sun Storage & Archiving Management File System
 *
 *      Copyright (c) 2007 Sun Microsystems, Inc.
 *      All Rights Reserved.
 *
 *      Government Rights Notice
 *      Use, duplication, or disclosure by the U.S. Government is
 *      subject to restrictions set forth in the Sun Microsystems,
 *      Inc. license agreements and as provided in DFARS 227.7202-1(a)
 *      and 227.7202-3(a) (1995), DRAS 252.227-7013(c)(ii) (OCT 1988),
 *      FAR 12.212(a)(1995), FAR 52.227-19, or FAR 52.227-14 (ALT III),
 *      as applicable.  Sun Microsystems, Inc.
 *
 *    SAM-QFS_notice_end
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <sys/types.h>
#include <sys/time.h>
#include "stat.h"
#include "samrpc.h"


bool_t
xdr_filecmd(
register XDR *xdrs,
filecmd *objp)
{
	register long *buf;

	if (!xdr_string(xdrs, &objp->filename, MAXPATHLEN))
		return(FALSE);
	if (!xdr_string(xdrs, &objp->options, MAX_OPTS))
		return(FALSE);
	return(TRUE);
}

bool_t
xdr_statcmd(
register XDR *xdrs,
statcmd *objp)
{
	register long *buf;

	if (!xdr_string(xdrs, &objp->filename, MAXPATHLEN))
		return(FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return(FALSE);
	return(TRUE);
}

bool_t
xdr_sam_st(
register XDR *xdrs,
sam_st *objp)
{
	register long *buf;

	if (!xdr_int(xdrs, &objp->result))
		return(FALSE);
	if (!xdr_samstat_t(xdrs, &objp->s))
		return(FALSE);
	return(TRUE);
}


bool_t
xdr_samcopy(
register XDR *xdrs,
samcopy *objp)
{
	register long *buf;

	int i;
	if (!xdr_ushort_t(xdrs, &objp->flags))
		return(FALSE);
	if (!xdr_short(xdrs, &objp->n_vsns))
		return(FALSE);
	if (!xdr_u_long(xdrs, (ulong *)&objp->creation_time))
		return(FALSE);
	if (!xdr_u_longlong_t(xdrs, &objp->position))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->offset))
		return(FALSE);
	if (!xdr_vector(xdrs, (char *)objp->media, 4,
		sizeof(char), (xdrproc_t)xdr_char))
			return(FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vsn, MAX_VSN,
		sizeof(char), (xdrproc_t)xdr_char))
		return(FALSE);
	return(TRUE);
}


bool_t
xdr_samstat_t(
register XDR *xdrs,
samstat_t *objp)
{
	int i;

	if (!xdr_u_long(xdrs, &objp->st_mode))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->st_ino))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->st_dev))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->st_nlink))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->st_uid))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->st_gid))
		return(FALSE);
	if (!xdr_u_longlong_t(xdrs, &objp->st_size))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->st_atime))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->st_mtime))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->st_ctime))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->attribute_time))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->creation_time))
		return(FALSE);
	if (!xdr_long(xdrs, (long *)&objp->residence_time))
		return(FALSE);
	if (!xdr_vector(xdrs, (char *)objp->copy, MAX_ARCHIVE,
			sizeof(samcopy), (xdrproc_t)xdr_samcopy))
		return(FALSE);
	if (!xdr_uint_t(xdrs, &objp->attr))
		return(FALSE);
	if (!xdr_u_char(xdrs, &objp->cs_algo))
		return(FALSE);
	if (!xdr_u_char(xdrs, &objp->flags))
		return(FALSE);
	if (!xdr_u_char(xdrs, &objp->stripe_width))
		return(FALSE);
	if (!xdr_u_char(xdrs, &objp->stripe_group))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->gen))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->partial_size))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->rdev))
		return(FALSE);
	if (!xdr_u_longlong_t(xdrs, &objp->st_blocks))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->segment_size))
		return(FALSE);
	if (!xdr_u_long(xdrs, &objp->segment_number))
		return(FALSE);
	if (!xdr_uint_t(xdrs, &objp->stage_ahead))
		return(FALSE);
	return(TRUE);
}
